---
title: "hw_2"
author: "Ching-Yung Chang"
date: "9/25/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

???????????????https://www.imdb.com/title/tt0848228/?ref_=nv_sr_1

??????Chrome??????SelectorGadget???????????????CSS??????
??????rvest????????????????????????????????????????????????????????????
?????????.html??????R Markdown ??????
??????rvest????????????????????????

```{r}
library("rvest")
```

```{r}
The_avengers <- read_html("https://www.imdb.com/title/tt0848228/?ref_=nv_sr_1")
rating <- The_avengers %>%
    html_nodes("strong span") %>%
    html_text() %>%
    as.numeric()
rating
```

??????SelectorGadget???????????????????????????????????????????????????????????????????????????/??????????????????????????????

```{r}
#?????????????????????
poster <- The_avengers %>%
    html_nodes(".poster img") %>%
    html_attr("src")
poster
```

```{r}
#????????????
budget <- The_avengers %>%
    html_nodes('#titleDetails .txt-block:nth-child(12)') %>%
    html_text()
budget
```

```{r}
#?????????????????????
Opening_Weekend_USA <- The_avengers %>%
    html_nodes('#titleDetails .txt-block:nth-child(13)') %>%
    html_text()
Opening_Weekend_USA
```

```{r}
#????????????
Gross_USA <- The_avengers %>%
    html_nodes('#titleDetails .txt-block:nth-child(14)') %>%
    html_text()
Gross_USA
```

```{r}
#????????????
Cumulative_Worldwide_Gross <- The_avengers %>%
    html_nodes('#titleDetails .txt-block:nth-child(15)') %>%
    html_text()
Cumulative_Worldwide_Gross
```

```{r}
#???????????????
time <- The_avengers %>%
    html_nodes('#titleDetails .txt-block:nth-child(23)') %>%
    html_text()
time
```

