---
title: "hw3_avocado"
author: "Ching-Yung Chang"
date: "10/3/2018"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```



```{r}
library(ggplot2)
library(hexbin)
library(dplyr)
my_data <- read.csv("Downloads/avocado.csv", header=T, sep=",")
my_data
```



```{r pressure, echo=FALSE}
ggplot(data = my_data, mapping = aes(x = Total.Volume, y = AveragePrice)) + geom_point(alpha = 0.1, color = "brown")
my_data[my_data$type == 'conventional']
head(my_data, 20)
class(my_data)
str(my_data)
summary(my_data)
colume_name <- colnames(my_data)
colume_name
```



```{r}
ggplot(data = my_data, mapping = aes(x = type)) + geom_bar(color = "brown")
ggplot(data = my_data, mapping = aes(x = Total.Bags, y = AveragePrice)) + geom_bar(stat = "identity", color = "brown")
ggplot(data = my_data, mapping = aes(x = year, y = Total.Bags))+geom_bar(stat="identity",fill="steelblue")
ggplot(data = my_data, mapping = aes(x = year, y = AveragePrice/338))+geom_bar(stat="identity",fill="steelblue")

```



```{r}
my_data_organic <- my_data[grep("organic", my_data$type), ]
grep("organic", my_data$type)
View(my_data_organic)
```


```{r}

```


```{r}

```


```{r}

```


```{r}

```

